<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropMaritalStatus</name>
   <tag></tag>
   <elementGuidId>8856850b-4d46-480c-876c-2e133cabd5c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='personalInfo']/tbody/tr[2]/td/input[@id=&quot;3d64386e-33e0-4919-bba7-790804bcea7c&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
