<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>genderFemale</name>
   <tag></tag>
   <elementGuidId>5d377cfc-8e0d-4c9c-bb08-f421d07486e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='personalInfo']/tbody/tr[1]/td/input[@id=&quot;e3a6c9c2-83a0-4d97-ab75-d1015b60d89e&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
