<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtIDNo</name>
   <tag></tag>
   <elementGuidId>898a0f47-7841-461a-bb15-9da6cfa272ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='personalInfo']/tbody/tr[3]/td/input[@id=&quot;096d139b-4de2-425c-9289-a6120da0a485&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
